In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame 
import nltk

from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from scipy.spatial.distance import cosine
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

import re
import string
from sklearn.metrics import mean_squared_error

In [2]:
df= pd.read_json("Automotive_5.json",lines = True)


In [3]:
# print(df.columns)
# print(df.shape)

In [4]:
df = df[['asin','overall','reviewerID']].copy()

In [250]:
# print(df)

In [251]:
df_original = df.copy()
df = df.pivot(index = "asin" , columns = "reviewerID" , values = "overall")

In [252]:
X = df.values
# X

In [253]:
Y = df.sum(axis =1)
# Y

In [254]:
Z =df.count(axis =1).astype('float64')
# Z

In [255]:
Y = Y.div(Z,axis=0)
# Y

In [262]:
df_new = df.sub(Y,axis=0).fillna(0)
df_new

reviewerID  A00473363TJ8YSZ3YAGG9  A0473259F6GQNBD88IYN  \
asin                                                      
B00002243X                    0.0                   0.0   
B00002243Z                    0.0                   0.0   
B00008BKX5                    0.0                   0.0   
B00008RW9U                    0.0                   0.0   
B00008RW9V                    0.0                   0.0   
B00009RAX7                    0.0                   0.0   
B00009W3G7                    0.0                   0.0   
B0000ATZD5                    0.0                   0.0   
B0000ATZDE                    0.0                   0.0   
B0000AXNMO                    0.0                   0.0   
B0000AXPDU                    0.0                   0.0   
B0000AXRH5                    0.0                   0.0   
B0000AXTUY                    0.0                   0.0   
B0000AXU02                    0.0                   0.0   
B0000AXY62                    0.0                   0.0   
B0000AY3X0                    0.0                   0.0   
B0000AY60S                    0.0                   0.0   
B0000AY9W6                    0.0                   0.0   
B0000AYES4                    0.0                   0.0   
B0000AZ9KS                    0.0                   0.0   
B0000DYVN9                    0.0                   0.0   
B0000UUX34                    0.0                   0.0   
B000182DPG                    0.0                   0.0   
B0001L0DFA                    0.0                   0.0   
B00020CATC                    0.0                   0.0   
B00020CAUG                    0.0                   0.0   
B00020CAVA                    0.0                   0.0   
B00020CB2S                    0.0                   0.0   
B000221M94                    0.0                   0.0   
B00026Z3DQ                    0.0                   0.0   
...                           ...                   ...   
B00DBH8W4K                    0.0                   0.0   
B00DJ5KEF4                    0.0                   0.0   
B00DKU2V1I                    0.0                   0.0   
B00DL6T2YK                    0.0                   0.0   
B00EDWF1BE                    0.0                   0.0   
B00EVY2SKG                    0.0                   0.0   
B00EVY344K                    0.0                   0.0   
B00F5LWJBC                    0.0                   0.0   
B00FDQPCR2                    0.0                   0.0   
B00FF1K7BQ                    0.0                   0.0   
B00FJDL0J8                    0.0                   0.0   
B00FJXKE5E                    0.0                   0.0   
B00FLSG6V8                    0.0                   0.0   
B00FRZPN64                    0.0                   0.0   
B00FSIN0U6                    0.0                   0.0   
B00G25GOCA                    0.0                   0.0   
B00G49DUJY                    0.0                   0.0   
B00G49DVGG                    0.0                   0.0   
B00G49NYKY                    0.0                   0.0   
B00G49NYT0                    0.0                   0.0   
B00GG9FB8U                    0.0                   0.0   
B00H72YE7Y                    0.0                   0.0   
B00H72YG9U                    0.0                   0.0   
B00HJ6OBIK                    0.0                   0.0   
B00HJ6OBUI                    0.0                   0.0   
B00HWIZO6I                    0.0                   0.0   
B00I93BOZ0                    0.0                   0.0   
B00JGM7Z5Q                    0.0                   0.0   
B00JGP8I1S                    0.0                   0.0   
B00KIAQ8VW                    0.0                   0.0   

reviewerID  A09567722SXKYZTV7OFCJ  A10063PJ5C9WQQ  A100UD67AHFODS  \
asin                                                                
B00002243X                    0.0             0.0            0.00   
B00002243Z                    0.0             0.0            0.00   
B00008

In [263]:
from sklearn.model_selection import train_test_split
df_newone = np.array(df_new)
# X_train, X_split = train_test_split(df_newone,test_size = 0.20)
tpercent = 0.8
tsize = int(np.floor(tpercent * len(df_newone)))
X_train = df_newone[:tsize]
X_split = df_newone[tsize:]
#len of train and test
lentrain = len(X_train)
lentest = len(X_split)

In [264]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [265]:
X_split

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [266]:
# X_split

In [267]:
nbrs_train = NearestNeighbors(n_neighbors=5, algorithm='auto',metric = 'cosine').fit(X_train)

distances, indices = nbrs_train.kneighbors(X_train)


In [268]:
df_original = df_original.groupby("asin", as_index=False).mean()
# df_original

In [269]:

for i in range(len(X_split)):
    a = nbrs_train.kneighbors([X_split[i]])
    related_product_list = a[1]

    first_related_product = [item[0] for item in related_product_list]
    first_related_product = str(first_related_product).strip('[]')
    first_related_product = int(first_related_product)
    second_related_product = [item[1] for item in related_product_list]
    second_related_product = str(second_related_product).strip('[]')
    second_related_product = int(second_related_product)
    
#     print ("Based on product reviews, for ", df_original["asin"][len(X_train) + i] ," average rating is ",df_original["overall"][len(X_train) + j])
#     print ("The first similar product is ", df_original["asin"][first_related_product] ," average rating is ",df_original["overall"][first_related_product])
#     print ("The second similar product is ", df_original["asin"][second_related_product] ," average rating is ",df_original["overall"][second_related_product])
#     print ("-----------------------------------------------------------")
    

In [220]:
df5_train_target = df_original["overall"][:len(X_train)]
df5_test_target = df_original["overall"][len(X_train):len(X_train)+len(X_split)]
df5_train_target = df5_train_target.astype(int)
df5_test_target = df5_test_target.astype(int)

n_neighbors = 3
knnclf = neighbors.KNeighborsClassifier(n_neighbors, weights='distance')
knnclf.fit(X_train, df5_train_target)
knnpreds_test = knnclf.predict(X_split)

print(classification_report(df5_test_target, knnpreds_test))

             precision    recall  f1-score   support

          1       0.00      0.00      0.00         3
          2       0.05      0.06      0.05        18
          3       0.27      0.18      0.21       187
          4       0.69      0.80      0.74       493
          5       0.00      0.00      0.00        13

avg / total       0.55      0.60      0.57       714



/home/vidit/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [221]:
print (accuracy_score(df5_test_target, knnpreds_test))

0.5980392156862745


In [85]:
temp_mat = df_new.values
temp_mat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [86]:
nbrs = NearestNeighbors(n_neighbors=5, algorithm='auto').fit(temp_mat)

In [88]:
distances, indices = nbrs.kneighbors(temp_mat)

In [89]:
indices

array([[   0,  633,  634,  649,  640],
       [   1,  454,   18,   21,   12],
       [   2,  454,   18,   21,   12],
       ...,
       [1832, 1783, 1792, 1800, 1793],
       [1833,  286,  292,  299,  289],
       [1834, 1604,  618,  461,  476]])