In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame 
import nltk

from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from scipy.spatial.distance import cosine
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

import re
import string
from sklearn.metrics import mean_squared_error

In [2]:
df= pd.read_json("Automotive_5.json",lines = True)

In [3]:
df = df[['asin','overall','reviewerID']].copy()

In [4]:
from sklearn.model_selection import train_test_split
# Splitting train and test data at the start
df_train, df_test = train_test_split(df,test_size=0.2)
df_train = df_train.sort_index(axis=0)

In [5]:
len(df_train)

16378

In [6]:
len(df_test)

4095

In [7]:
# df_original contains the copy of training sampy before pivoting 
df_original_train = df_train.copy()
df_train = df_train.pivot(index = "asin" , columns = "reviewerID" , values = "overall")
df_train = df_train.sort_index(axis=1)

In [8]:
df_train.shape

(1834, 2926)

In [9]:
df_test.pivot(index = "asin" , columns = "reviewerID" , values = "overall").shape

(1524, 2209)

In [10]:
# In this blockck we are normalizing each rows

X = df_train.values
Y = df_train.sum(axis = 1)
Z =df_train.count(axis =1).astype('float64')
Y = Y.div(Z,axis=0)

df_new_train = df_train.sub(Y,axis=0).fillna(0)

In [11]:
# fitting training data into our nearest neighbor model
nbrs_train = NearestNeighbors(n_neighbors= 5, algorithm='auto',metric = 'cosine').fit(df_new_train.values)

In [12]:
# getting nmeighbors and their distances for each column
distances, indices = nbrs_train.kneighbors(df_new_train,return_distance=True)

In [13]:
distances

array([[0.00000000e+00, 6.73401368e-01, 9.35450278e-01, 9.35450278e-01,
        9.42264973e-01],
       [2.22044605e-16, 7.64297740e-01, 7.64297740e-01, 7.95875855e-01,
        8.50928802e-01],
       [0.00000000e+00, 7.37928791e-01, 7.90343033e-01, 8.18431740e-01,
        8.55456383e-01],
       ...,
       [2.22044605e-16, 6.66666667e-01, 7.56024982e-01, 8.55693263e-01,
        9.09612309e-01],
       [0.00000000e+00, 5.96352834e-01, 7.98850575e-01, 8.38993178e-01,
        8.65985933e-01],
       [0.00000000e+00, 7.44588764e-01, 8.31244435e-01, 8.72294382e-01,
        9.11166907e-01]])

In [14]:
indices

array([[   0,   67,  572, 1053,  626],
       [   1, 1750,  662, 1211, 1492],
       [   2, 1227,  411, 1680,  208],
       ...,
       [1831, 1603, 1797, 1769,   20],
       [1832,  169,  343,  465, 1172],
       [1833, 1603, 1377,  365, 1528]])

In [15]:
df_train

reviewerID  A00473363TJ8YSZ3YAGG9  A0473259F6GQNBD88IYN  \
asin                                                      
B00002243X                    NaN                   NaN   
B00002243Z                    NaN                   NaN   
B00008BKX5                    NaN                   NaN   
B00008RW9U                    NaN                   NaN   
B00008RW9V                    NaN                   NaN   
B00009RAX7                    NaN                   NaN   
B00009W3G7                    NaN                   NaN   
B0000ATZD5                    NaN                   NaN   
B0000ATZDE                    NaN                   NaN   
B0000AXNMO                    NaN                   NaN   
B0000AXPDU                    NaN                   NaN   
B0000AXRH5                    NaN                   NaN   
B0000AXTUY                    NaN                   NaN   
B0000AXU02                    NaN                   NaN   
B0000AXY62                    NaN                   NaN   
B0000AY3X0                    NaN                   NaN   
B0000AY60S                    NaN                   NaN   
B0000AY9W6                    NaN                   NaN   
B0000AYES4                    NaN                   NaN   
B0000AZ9KS                    NaN                   NaN   
B0000DYVN9                    NaN                   NaN   
B0000UUX34                    NaN                   NaN   
B000182DPG                    NaN                   NaN   
B0001L0DFA                    NaN                   NaN   
B00020CATC                    NaN                   NaN   
B00020CAUG                    NaN                   NaN   
B00020CAVA                    NaN                   NaN   
B00020CB2S                    NaN                   NaN   
B000221M94                    NaN                   NaN   
B00026Z3DQ                    NaN                   NaN   
...                           ...                   ...   
B00DBH8W4K                    NaN                   NaN   
B00DJ5KEF4                    NaN                   NaN   
B00DKU2V1I                    NaN                   NaN   
B00DL6T2YK                    NaN                   NaN   
B00EDWF1BE                    NaN                   NaN   
B00EVY2SKG                    NaN                   NaN   
B00EVY344K                    NaN                   NaN   
B00F5LWJBC                    NaN                   NaN   
B00FDQPCR2                    NaN                   NaN   
B00FF1K7BQ                    NaN                   NaN   
B00FJDL0J8                    NaN                   NaN   
B00FJXKE5E                    NaN                   NaN   
B00FLSG6V8                    NaN                   NaN   
B00FRZPN64                    NaN                   NaN   
B00FSIN0U6                    NaN                   NaN   
B00G25GOCA                    NaN                   NaN   
B00G49DUJY                    NaN                   NaN   
B00G49DVGG                    NaN                   NaN   
B00G49NYKY                    NaN                   NaN   
B00G49NYT0                    NaN                   NaN   
B00GG9FB8U                    NaN                   NaN   
B00H72YE7Y                    NaN                   NaN   
B00H72YG9U                    NaN                   NaN   
B00HJ6OBIK                    NaN                   NaN   
B00HJ6OBUI                    NaN                   NaN   
B00HWIZO6I                    NaN                   NaN   
B00I93BOZ0                    NaN                   NaN   
B00JGM7Z5Q                    NaN                   NaN   
B00JGP8I1S                    NaN                   NaN   
B00KIAQ8VW                    NaN                   NaN   

reviewerID  A09567722SXKYZTV7OFCJ  A10063PJ5C9WQQ  A100UD67AHFODS  \
asin                                                                
B00002243X                    NaN             NaN             NaN   
B00002243Z                    NaN             NaN             NaN   
B00008

In [16]:
# creating list for average ratings of all items
item_avg = df_original_train.groupby(['asin']).mean()


In [17]:
# creating list for average ratings for all users
user_avg = df_original_train.groupby(['reviewerID']).mean()

In [18]:
# calculating the mean average rating for all items and all dataset
mean_avg = df_original_train["overall"].mean()

In [105]:
# Now we have everything, we strat testing
df_test[4:5]

asin  overall      reviewerID
14985  B003IS3HV0        5  A17OSOO1PIUG7U

In [136]:
# This item maps basically maps items with its index in training matrix so that based on that index we can get vectors from distances and indices

item_map = df_new_train.index.values
item_map.shape

(1834,)

In [107]:

#  Now this is for finding our item which we are testing in itemmap
i, =np.where(item_map == df_test[4:5]["asin"].iat[0])
i[0]

1315

In [108]:
# Once we get the item, we get the indices of its neighbors
indices[i[0]:i[0]+1]

array([[1315,  581,  336, 1003,  114]])

In [109]:
# the distances of those neighbors
distances[i[0]:i[0]+1]

array([[2.22044605e-16, 4.30463402e-01, 6.20017881e-01, 7.53597310e-01,
        8.49811125e-01]])

In [111]:
indices[1315:1316][0][1]

581

In [121]:
# this step here checks for each item , if the user has rated that item in its neighborhood,
# if so, this step returns the tuple from our original training set, and we need to extract rating from that. 
# SO here we need to loop over all the neighbors and find the tuples, if available,
# then sum it over based on the given formula 
# I hope I am clear, if any doubts just give me a call


temp = df_original_train.loc[(df_original_train['asin'] == item_map[indices[1315:1316][0][4]]) &  (df_original_train['reviewerID'] == df_test[4:5]['reviewerID'].iat[0])]

temp

In [122]:
df_original_train.loc[(df_original_train['asin'] == item_map[indices[1315:1316][0][4]])]

asin  overall      reviewerID
1253  B0002STSQM        5  A2PKXORLQOXFJX
1254  B0002STSQM        5   A9BVHFGX28SNZ
1255  B0002STSQM        5  A1MV2GGCYD2AFQ
1256  B0002STSQM        4   A4ONPTKOHKXPB
1258  B0002STSQM        3  A36HBGDEFPWD0U
1262  B0002STSQM        5  A3CJ7AEE7H6A1M
1263  B0002STSQM        4  A17CXXQUDPQASN
1264  B0002STSQM        5  A254EBBW0W3SOW
1265  B0002STSQM        4   ATXS5PY1QV2UO
1266  B0002STSQM        5  A1XRENC5BHV5GB
1267  B0002STSQM        5  A3GT2EWQSO45ZG
1268  B0002STSQM        5  A1MEJ80JTZQCQA
1269  B0002STSQM        5  A3ETIHCNQX77Y6
1270  B0002STSQM        5  A1WI2GU6SPDSCU
1271  B0002STSQM        1  A36DFLISBU97Z4
1272  B0002STSQM        5  A3I42CDG116KKQ
1273  B0002STSQM        5  A3NH0RRMYJQASN
1275  B0002STSQM        5  A3NHDLYNUIRXYP
1276  B0002STSQM        4  A2M7L6LMYU1DV9
1277  B0002STSQM        5   AYYZH8KL2Y6D3
1278  B0002STSQM        5  A2PICNZWHEINQC
1279  B0002STSQM        4  A3FJTBSTMW8U53
1280  B0002STSQM        5   A1MDVYDLJNCKA
1281  B0002STSQM        5  A38OO05LV8XICY
1282  B0002STSQM        5   AM1WUDYVK9ZH8
1283  B0002STSQM        5  A34FFE15ZG8JK1
1284  B0002STSQM        4  A11IW3NNICDT8I
1286  B0002STSQM        5   AQBJQG8EQEEL6
1287  B0002STSQM        5  A2SYP5UDYEGQVM
1288  B0002STSQM        3  A14I0X9ZNK9D83
1289  B0002STSQM        5   AQZ64R6S3R1VF
1290  B0002STSQM        5  A3FQWIO6UOXF4X
1291  B0002STSQM        5  A3KBUTSIFX0K9V
1292  B0002STSQM        5  A2OB0IK83HTU18
1293  B0002STSQM        5  A2GPQZHM465OUK
1294  B0002STSQM        4  A3112D9P7HXV0E
1295  B0002STSQM        4  A25UBYD3S1AWJ4
1296  B0002STSQM        5  A343LYS4IEVHBM

In [115]:
temp

Empty DataFrame
Columns: [asin, overall, reviewerID]
Index: []

In [124]:
# This is mean avg rating
mean_avg

4.468127976553914

In [132]:
bi = item_avg.loc["B003IS3HV0"]['overall'] - mean_avg

In [133]:
bx = user_avg.loc["A17OSOO1PIUG7U"]['overall'] - mean_avg

In [134]:
mean_avg + bi + bx

4.750919642493704