In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import DataFrame 
import nltk

from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from scipy.spatial.distance import cosine
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

import re
import string
from sklearn.metrics import mean_squared_error

In [2]:
df= pd.read_json("Automotive_5.json",lines = True)

In [3]:
df = df[['asin','overall','reviewerID']].copy()

In [4]:
from sklearn.model_selection import train_test_split
# Splitting train and test data at the start
df_train, df_test = train_test_split(df,test_size=0.2)
df_train = df_train.sort_index(axis=0)

In [5]:
len(df_train)

16378

In [6]:
len(df_test)

4095

In [7]:
# df_original contains the copy of training sampy before pivoting 
df_original_train = df_train.copy()
df_train = df_train.pivot(index = "asin" , columns = "reviewerID" , values = "overall")
df_train = df_train.sort_index(axis=1)

In [8]:
df_train.shape

(1834, 2928)

In [9]:
df_test.pivot(index = "asin" , columns = "reviewerID" , values = "overall").shape

(1502, 2232)

In [10]:
# In this blockck we are normalizing each rows

X = df_train.values
Y = df_train.sum(axis = 1)
Z =df_train.count(axis =1).astype('float64')
Y = Y.div(Z,axis=0)

df_new_train = df_train.sub(Y,axis=0).fillna(0)

In [11]:
# fitting training data into our nearest neighbor model
nbrs_train = NearestNeighbors(n_neighbors= 5, algorithm='auto',metric = 'cosine').fit(df_new_train.values)

In [12]:
# getting nmeighbors and their distances for each column
distances, indices = nbrs_train.kneighbors(df_new_train,return_distance=True)

In [13]:
distances

array([[0.00000000e+00, 6.88195218e-01, 9.40238570e-01, 9.48499819e-01,
        9.48565550e-01],
       [0.00000000e+00, 6.46446609e-01, 8.15362764e-01, 8.40099463e-01,
        8.41886117e-01],
       [2.22044605e-16, 6.64589803e-01, 8.21205031e-01, 9.14862921e-01,
        9.15484575e-01],
       ...,
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00],
       [0.00000000e+00, 7.65471069e-01, 8.46225269e-01, 8.72338620e-01,
        9.24083402e-01],
       [0.00000000e+00, 7.81888067e-01, 8.28272625e-01, 8.43235072e-01,
        8.66892738e-01]])

In [14]:
indices

array([[   0,   67, 1127,  735,  437],
       [   1,  663, 1211,  109, 1492],
       [   2,  209,  581,   51,  842],
       ...,
       [1222, 1220, 1224, 1221, 1225],
       [1832,  169, 1172,  812,  755],
       [1833,  618,  366, 1603, 1377]])

In [15]:
df_train

reviewerID  A00473363TJ8YSZ3YAGG9  A0473259F6GQNBD88IYN  \
asin                                                      
B00002243X                    NaN                   NaN   
B00002243Z                    NaN                   NaN   
B00008BKX5                    NaN                   NaN   
B00008RW9U                    NaN                   NaN   
B00008RW9V                    NaN                   NaN   
B00009RAX7                    NaN                   NaN   
B00009W3G7                    NaN                   NaN   
B0000ATZD5                    NaN                   NaN   
B0000ATZDE                    NaN                   NaN   
B0000AXNMO                    NaN                   NaN   
B0000AXPDU                    NaN                   NaN   
B0000AXRH5                    NaN                   NaN   
B0000AXTUY                    NaN                   NaN   
B0000AXU02                    NaN                   NaN   
B0000AXY62                    NaN                   NaN   
B0000AY3X0                    NaN                   NaN   
B0000AY60S                    NaN                   NaN   
B0000AY9W6                    NaN                   NaN   
B0000AYES4                    NaN                   NaN   
B0000AZ9KS                    NaN                   NaN   
B0000DYVN9                    NaN                   NaN   
B0000UUX34                    NaN                   NaN   
B000182DPG                    NaN                   NaN   
B0001L0DFA                    NaN                   NaN   
B00020CATC                    NaN                   NaN   
B00020CAUG                    NaN                   NaN   
B00020CAVA                    NaN                   NaN   
B00020CB2S                    NaN                   NaN   
B000221M94                    NaN                   NaN   
B00026Z3DQ                    NaN                   NaN   
...                           ...                   ...   
B00DBH8W4K                    NaN                   NaN   
B00DJ5KEF4                    NaN                   NaN   
B00DKU2V1I                    NaN                   NaN   
B00DL6T2YK                    NaN                   NaN   
B00EDWF1BE                    NaN                   NaN   
B00EVY2SKG                    NaN                   NaN   
B00EVY344K                    NaN                   NaN   
B00F5LWJBC                    NaN                   NaN   
B00FDQPCR2                    NaN                   NaN   
B00FF1K7BQ                    NaN                   NaN   
B00FJDL0J8                    NaN                   NaN   
B00FJXKE5E                    NaN                   NaN   
B00FLSG6V8                    NaN                   NaN   
B00FRZPN64                    NaN                   NaN   
B00FSIN0U6                    NaN                   NaN   
B00G25GOCA                    NaN                   NaN   
B00G49DUJY                    NaN                   NaN   
B00G49DVGG                    NaN                   NaN   
B00G49NYKY                    NaN                   NaN   
B00G49NYT0                    NaN                   NaN   
B00GG9FB8U                    NaN                   NaN   
B00H72YE7Y                    NaN                   NaN   
B00H72YG9U                    NaN                   NaN   
B00HJ6OBIK                    NaN                   NaN   
B00HJ6OBUI                    NaN                   NaN   
B00HWIZO6I                    NaN                   NaN   
B00I93BOZ0                    NaN                   NaN   
B00JGM7Z5Q                    NaN                   NaN   
B00JGP8I1S                    NaN                   NaN   
B00KIAQ8VW                    NaN                   NaN   

reviewerID  A09567722SXKYZTV7OFCJ  A10063PJ5C9WQQ  A100UD67AHFODS  \
asin                                                                
B00002243X                    NaN             NaN             NaN   
B00002243Z                    NaN             NaN             NaN   
B00008

In [16]:
# creating list for average ratings of all items
item_avg = df_original_train.groupby(['asin']).mean()


In [17]:
# creating list for average ratings for all users
user_avg = df_original_train.groupby(['reviewerID']).mean()

In [18]:
# calculating the mean average rating for all items and all dataset
mean_avg = df_original_train["overall"].mean()

In [19]:
# Now we have everything, we strat testing
df_test[4:5]

asin  overall      reviewerID
4279  B000BC976K        5  A37DXIENIDHTVY

In [20]:
# This item maps basically maps items with its index in training matrix so that based on that index we can get vectors from distances and indices

item_map = df_new_train.index.values
item_map.shape

(1834,)

In [21]:

#  Now this is for finding our item which we are testing in itemmap
i, =np.where(item_map == df_test[4:5]["asin"].iat[0])
i[0]

346

In [22]:
# Once we get the item, we get the indices of its neighbors
indices[i[0]:i[0]+1]

array([[ 346, 1081, 1511, 1756, 1082]])

In [23]:
# the distances of those neighbors
distances[i[0]:i[0]+1]

array([[0.        , 0.42184841, 0.87525348, 0.88214887, 0.90871291]])

In [24]:
indices[1315:1316][0][1]

332

In [25]:
# this step here checks for each item , if the user has rated that item in its neighborhood,
# if so, this step returns the tuple from our original training set, and we need to extract rating from that. 
# SO here we need to loop over all the neighbors and find the tuples, if available,
# then sum it over based on the given formula 
# I hope I am clear, if any doubts just give me a call


temp = df_original_train.loc[(df_original_train['asin'] == item_map[indices[1315:1316][0][4]]) &  (df_original_train['reviewerID'] == df_test[4:5]['reviewerID'].iat[0])]

temp

In [26]:
df_original_train.loc[(df_original_train['asin'] == item_map[indices[1315:1316][0][4]])]

asin  overall      reviewerID
16536  B004G5FKO6        4  A3AYSYSLHU26U9
16537  B004G5FKO6        4   ADY836HK6QSYR
16538  B004G5FKO6        5  A17OSOO1PIUG7U
16539  B004G5FKO6        4  A2CZPM110DW516
16540  B004G5FKO6        4  A1P5QZJB3QWL0B
16541  B004G5FKO6        4  A3FARCKMBHQZLY
16542  B004G5FKO6        3  A3VI2VETB90ZG5
16547  B004G5FKO6        4  A38ON1MOZNBCGE
16548  B004G5FKO6        4   ABNMD6670TV53
16549  B004G5FKO6        4  A30Z0GG96D11EO

In [27]:
temp

Empty DataFrame
Columns: [asin, overall, reviewerID]
Index: []

In [28]:
# This is mean avg rating
mean_avg

4.470631334717304

In [29]:
bi = item_avg.loc["B003IS3HV0"]['overall'] - mean_avg

In [30]:

bx = user_avg.loc["A17OSOO1PIUG7U"]['overall'] - mean_avg

In [31]:
mean_avg + bi + bx

4.719844855758887

In [74]:
# basically we need to completely this loop
prediction_arr = []

for i in range(len(df_test)):
#     item = np.where(item_map == df_test[i:i+1]["asin"].iat[0])
#     item _ nbrs = indices[item[0]:item[0] + 1]
#     nbrs_distances = distances[item[0]:item[0] + 1]
    
    item_asin = df_test[i:i+1]['asin'].iat[0]
    item_userID = df_test[i:i+1]['reviewerID'].iat[0]
    actual_rating = df_test[i:i+1]['overall'].iat[0]
    
    predicted_rating = 0
    if item_asin in item_avg:
        bi = item_avg.loc[item_asin]['overall'] - mean_avg
    else:
        bi = 0
    if item_userID in user_avg:
        bx = user_avg.loc[item_userID]['overall'] - mean_avg
    else:
        bx = 0
            
    baseline_estimate = mean_avg + bi + bx
    predicted_rating = baseline_estimate
    
    numerator = 0 
    denomenator = 0
    
    if bi:
        item  = np.where(item_map == df_test[i:i+1]["asin"].iat[0])[0][0]
        item_nbrs = indices[item:item+1]
        dist_nbrs = distances[item:item+1]

        cnt = 0;
        for j in item_nbrs:
            temp = df_original_train.loc[(df_original_train['asin'] == item_map[j[0]]) &  (df_original_train['reviewerID'] == item_userID)]
            if(temp.size != 0):
                dist = dist_nbrs[cnt:cnt+1]
    #             print(temp['overall'].values[0])
                numerator += ((1 - dist[j])*(temp['overall'].values[0] - (item_avg.loc[temp['asin']]['overall'] - mean_avg) ))

                denomenator += (1 - dist)
    #             predicted_rating += (dist*temp['overall'].values[0])/dist
            cnt = cnt + 1

        if denomenator:
            predicted_rating += numerator/denomenator 
    
    prediction_arr.append(predicted_rating)
#     print(predicted_rating)
#     print(actual_rating - predicted_rating)
    

In [75]:
len(prediction_arr)

4095

In [76]:
len(df_test)

4095

In [80]:
actual_arr = df_test['overall'].values

In [81]:
mean_squared_error(actual_arr,prediction_arr)

0.8692729177510375